In [1]:
import pandas as pd
from pathlib import Path
root = Path().cwd().parent
data = root / "data"
from src.ingestion.processing import read_structured_table
balance_files = sorted((data / "parsed_tables" / "tables").glob("AAA_2015_consolidated_balance_sheet*.csv"))
df = pd.concat([read_structured_table(path) for path in balance_files], ignore_index=True)
df.head(10)

,item_code,item_name_raw,item_name_normalized,value_raw,value,unit,ticker,year,period,report_type,table_type,table_name,note_reference
0,110,I. Tiền và các khoản tương đương tiền,i. tien va cac khoan tuong duong tien,470.061.718.120,4.700617e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BANG CAN DOI KE TOAN,5.1
1,110,I. Tiền và các khoản tương đương tiền,i. tien va cac khoan tuong duong tien,336.807.716.067,3.368077e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BANG CAN DOI KE TOAN,5.1
2,111,1. Tiền,1. tien,242.393.182.850,2.423932e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN
3,111,1. Tiền,1. tien,122.985.042.067,1.229850e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN
4,112,2. Các khoản tương đương tiền,2. cac khoan tuong duong tien,227.668.535.270,2.276685e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN
5,112,2. Các khoản tương đương tiền,2. cac khoan tuong duong tien,213.822.674.000,2.138227e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN
6,120,II. Đầu tư tài chính ngắn hạn,ii. dau tu tai chinh ngan han,-,NaN,VND,AAA,2015,2015,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN
7,120,II. Đầu tư tài chính ngắn hạn,ii. dau tu tai chinh ngan han,30.000.000.000,3.000000e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN
8,123,1. Đầu tư nắm giữ đến ngày đáo hạn,1. dau tu nam giu den ngay dao han,-,NaN,VND,AAA,2015,2015,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN
9,123,1. Đầu tư nắm giữ đến ngày đáo hạn,1. dau tu nam giu den ngay dao han,30.000.000.000,3.000000e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BANG CAN DOI KE TOAN,NaN

In [7]:
df_new = pd.concat([read_structured_table(path) for path in balance_files], ignore_index=True)
df_new.head(50)

,item_code,item_name_raw,item_name_normalized,value_raw,value,unit,ticker,year,period,report_type,table_type,table_name,note_reference
0,100,A. TÀI SẢN NGĂN HẠN,a_tai_san_ngan_han,1.071.561.008.455,1.071561e+12,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
1,100,A. TÀI SẢN NGĂN HẠN,a_tai_san_ngan_han,694.379.188.147,6.943792e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
2,110,I. Tiền và các khoản tương đương tiền,i_tien_va_cac_khoan_tuong_duong_tien,470.061.718.120,4.700617e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.1
3,110,I. Tiền và các khoản tương đương tiền,i_tien_va_cac_khoan_tuong_duong_tien,336.807.716.067,3.368077e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.1
4,111,1. Tiền,1_tien,242.393.182.850,2.423932e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
5,111,1. Tiền,1_tien,122.985.042.067,1.229850e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
6,112,2. Các khoản tương đương tiền,2_cac_khoan_tuong_duong_tien,227.668.535.270,2.276685e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
7,112,2. Các khoản tương đương tiền,2_cac_khoan_tuong_duong_tien,213.822.674.000,2.138227e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
8,120,II. Đầu tư tài chính ngắn hạn,ii_dau_tu_tai_chinh_ngan_han,-,NaN,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
9,120,II. Đầu tư tài chính ngắn hạn,ii_dau_tu_tai_chinh_ngan_han,30.000.000.000,3.000000e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
10,123,1. Đầu tư nắm giữ đến ngày đáo hạn,1_dau_tu_nam_giu_den_ngay_dao_han,-,NaN,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
11,123,1. Đầu tư nắm giữ đến ngày đáo hạn,1_dau_tu_nam_giu_den_ngay_dao_han,30.000.000.000,3.000000e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
12,130,III. Các khoản phải thu ngắn hạn,iii_cac_khoan_phai_thu_ngan_han,363.509.670.487,3.635097e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
13,130,III. Các khoản phải thu ngắn hạn,iii_cac_khoan_phai_thu_ngan_han,179.292.636.069,1.792926e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
14,131,1. Phải thu ngắn hạn của khách hàng,1_phai_thu_ngan_han_cua_khach_hang,103.363.445.699,1.033634e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.2
15,131,1. Phải thu ngắn hạn của khách hàng,1_phai_thu_ngan_han_cua_khach_hang,122.485.772.971,1.224858e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.2
16,132,2. Trả trước cho người bán ngắn hạn,2_tra_truoc_cho_nguoi_ban_ngan_han,169.259.565.534,1.692596e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.3
17,132,2. Trả trước cho người bán ngắn hạn,2_tra_truoc_cho_nguoi_ban_ngan_han,4.571.973.920,4.571974e+09,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.3
18,136,3. Phải thu ngắn hạn khác,3_phai_thu_ngan_han_khac,91.048.764.635,9.104876e+10,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.4
19,136,3. Phải thu ngắn hạn khác,3_phai_thu_ngan_han_khac,52.396.579.838,5.239658e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.4
20,137,4. Dự phòng phải thu ngắn hạn khó đòi,4_du_phong_phai_thu_ngan_han_kho_doi,(162.105.381),-1.621054e+08,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
21,137,4. Dự phòng phải thu ngắn hạn khó đòi,4_du_phong_phai_thu_ngan_han_kho_doi,(162.105.381),-1.621054e+08,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
22,139,5. Tài sản thiếu chờ xử lý,5_tai_san_thieu_cho_xu_ly,-,NaN,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
23,139,5. Tài sản thiếu chờ xử lý,5_tai_san_thieu_cho_xu_ly,414.721,4.147210e+05,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
24,140,IV. Hàng tồn kho,iv_hang_ton_kho,214.186.555.570,2.141866e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.5
25,140,IV. Hàng tồn kho,iv_hang_ton_kho,137.522.087.909,1.375221e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.5
26,141,1. Hàng tồn kho,1_hang_ton_kho,214.186.555.570,2.141866e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
27,141,1. Hàng tồn kho,1_hang_ton_kho,137.522.087.909,1.375221e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
28,150,V. Tài sản ngắn hạn khác,v_tai_san_ngan_han_khac,23.803.064.278,2.380306e+10,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
29,150,V. Tài sản ngắn hạn khác,v_tai_san_ngan_han_khac,10.756.748.102,1.075675e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
30,151,1. Chi phí trả trước ngắn hạn,1_chi_phi_tra_truoc_ngan_han,14.690.447.772,1.469045e+10,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
31,151,1. Chi phí trả trước ngắn hạn,1_chi_phi_tra_truoc_ngan_han,8.286.725.798,8.286726e+09,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
32,152,2. Thuế GTGT được khấu trừ,2_thue_gtgt_duoc_khau_tru,9.112.616.506,9.112617e+09,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
33,152,2. Thuế GTGT được khấu trừ,2_thue_gtgt_duoc_khau_tru,1.177.133.335,1.177133e+09,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
34,153,3. Thuế và các khoản khác phải thu Nhà nước,3_thue_va_cac_khoan_khac_phai_thu_nha_nuoc,-,NaN,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.6
35,153,3. Thuế và các khoản khác phải thu Nhà nước,3_thue_va_cac_khoan_khac_phai_thu_nha_nuoc,1.292.888.969,1.292889e+09,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.6
36,200,B. TÀI SẢN DÀI HẠN,b_tai_san_dai_han,883.203.669.585,8.832037e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
37,200,B. TÀI SẢN DÀI HẠN,b_tai_san_dai_han,727.271.546.766,7.272715e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
38,220,I. Tài sản cố định,i_tai_san_co_dinh,636.532.208.633,6.365322e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
39,220,I. Tài sản cố định,i_tai_san_co_dinh,651.395.674.675,6.513957e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
40,221,1. Tài sản cố định hữu hình,1_tai_san_co_dinh_huu_hinh,595.375.421.956,5.953754e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.7
41,221,1. Tài sản cố định hữu hình,1_tai_san_co_dinh_huu_hinh,618.302.904.756,6.183029e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.7
42,222,- Nguyên giá,nguyen_gia,901.299.077.489,9.012991e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
43,222,- Nguyên giá,nguyen_gia,851.063.493.212,8.510635e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
44,223,- Giá trị hao mòn luỹ kế,gia_tri_hao_mon_luy_ke,(305.923.655.533),-3.059237e+11,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
45,223,- Giá trị hao mòn luỹ kế,gia_tri_hao_mon_luy_ke,(232.760.588.456),-2.327606e+11,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
46,227,2. Tài sản cố định vô hình,2_tai_san_co_dinh_vo_hinh,41.156.786.677,4.115679e+10,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.8
47,227,2. Tài sản cố định vô hình,2_tai_san_co_dinh_vo_hinh,33.092.769.919,3.309277e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,5.8
48,228,- Nguyên giá,nguyen_gia,45.206.131.504,4.520613e+10,VND,AAA,2015,2015,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>
49,228,- Nguyên giá,nguyen_gia,36.153.869.936,3.615387e+10,VND,AAA,2015,2014,consolidated,balance_sheet,BẢNG CÂN ĐỐI KẾ TOÁN HỢP NHẤT,<NA>